FROM nginx:1.26.0 as prod

# create empty file, which will be populated for preprod
RUN touch /etc/nginx/conf.d/user-media.conf

COPY nginx.conf /etc/nginx/
COPY statics.conf /etc/nginx/conf.d/
COPY cors.conf /etc/nginx/conf.d/
# template used for environment variables susbstitution
COPY nginx.conf.template /etc/nginx/templates/
COPY map_vars.conf.template /etc/nginx/templates/


RUN mkdir -p /log && touch /log/error.log && touch /log/access.log

COPY ./statics /statics

FROM prod as preprod
# let nginx host media to simulate remote storage from django's perspective
COPY user-media.conf /etc/nginx/conf.d/