app = 'cshock-library-nginx'
primary_region = 'sjc'

[build]
image = "registry.fly.io/cshock-library-nginx:latest"

# only need services if accessible from public internet (http_service automatically listens on ports
# 80 and 443 and adds a TCP-to-HTTP handler on port 80 and a TLS offloader and TCP-to-HTTP handler
# on port 443)
[http_service]
internal_port = 443
force_https = true
# if >1 machine: if enough machines not over connection soft limit, stop machine; if 1 machine: stops machine if no traffic.
# WARNING: makes debugging harder since you only have 5 minutes to debug before the machine is stopped
auto_stop_machines = true
# starts a machine if no machines running or all over connection soft limit
auto_start_machines = true
min_machines_running = 0
[http_service.http_options]
# couldn't get this configured to work with nginx without much more debugging
h2_backend = false
[http_service.tls_options]
# h2 and TLS offloading at the edge
alpn = ["h2", "http/1.1"]
versions = ["TLSv1.2", "TLSv1.3"]
default_self_signed = false

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1

[env]
# this gets populated by the fly.sh script
